;; -*- mode: eask; lexical-binding: t -*-

(package "code-shy-minor-mode"
         "1.0.0"
         "Auto code folding")

(website-url "https://github.com/jgrey4296/code-shy-minor-mode")
(keywords )

(package-file "code-shy-minor-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "vimish-fold")
(depends-on "s")
(depends-on "evil")
(depends-on "ivy")
(depends-on "f")
(depends-on "dash")
